const actions = {
  UPDATE_QUERY: "UPDATE_QUERY",
  UPDATE_LOADER: "UPDATE_LOADER",
  FETCH_ARTICLES_REQUEST: "FETCH_ARTICLES_REQUEST",
  FETCH_ARTICLES_SUCCESS: "FETCH_ARTICLES_SUCCESS",
  FETCH_ARTICLES_FAILURE: "FETCH_ARTICLES_FAILURE",
  FETCH_ARTICLES_CONTENT_REQUEST: "FETCH_ARTICLES_CONTENT_REQUEST",
  FETCH_ARTICLES_CONTENT_SUCCESS: "FETCH_ARTICLES_CONTENT_SUCCESS",
  FETCH_ARTICLES_CONTENT_FAILURE: "FETCH_ARTICLES_CONTENT_FAILURE",
};
export default actions;
